# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Devismart Add-on
version: "0.0.2"
slug: devismart
description: Devismart add-on
url: "https://github.com/bob-tm/ha-devismart-addon/"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
