# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Devismart Add-on
version: "0.0.17"
slug: devismart
description: Devismart add-on
url: "https://github.com/bob-tm/ha-devismart-addon/"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
init: false
webui: http://[HOST]:[PORT:8080]
map:
  - addon_config:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
ports:
  8080/tcp: 8080
